### ISSUE TITLE
Support for clojure 1.7.0-alpha2

### ISSUE THREAD

**Issue by sherpc** [venantius/ultra#22]
Hello! When I try to run lein repl with clojure 1.7.0-alpha2 project, I get this message before repl starts:

```
Boxed math warning, clojure/data/codec/base64.clj:26:31 - call: public static java.lang.Number clojure.lang.Numbers.unchecked_inc(java.lang.Object).
Boxed math warning, clojure/data/codec/base64.clj:255:16 - call: public static java.lang.Number clojure.lang.Numbers.remainder(java.lang.Object,long).
Boxed math warning, clojure/data/codec/base64.clj:255:9 - call: public static boolean clojure.lang.Numbers.isZero(java.lang.Object).
```

And none of ultra features works :(

**Comment by venantius** [comment]
This is an incompatibility with https://github.com/clojure/data.codec and Clojure 1.7.0 a2.

To be honest with you, I don't think I can prioritize compatibility with an alpha build at the moment. There are a few reasons why I'm looking forward to 1.7, one of which is that it'll enable cross-compatibility with Ultra and the various ClojureScript REPLs, but I'm afraid this is probably too early for me to take on. Still, if you're interested in ferreting it out and solving it, I'd start by talking @ataggart and/or @seancorfield, since they seem to be the maintainers of clojure/data.codec.

**Comment by sherpc** [comment]
Thanks for your response! Now I simply use 1.6 version.

вт, 24 февр. 2015, 20:00, Ursa americanus kermodei <notifications@github.com

**Comment by seancorfield** [comment]
FWIW 1, I'm not the maintainer of data.codec, I just added the standard CONTRIBUTING.md file to that repo, as I did to several other contrib repos.

FWIW 2, World Singles has 1.7.0 Alpha 5 in production and the Clojure Alphas have always been very stable for us (we've run Alphas in production since 1.3.0 Alpha 7!).
