### ISSUE TITLE
Colors not working on Windows

### ISSUE THREAD

**Issue by bpringe** [venantius/ultra#92]
I've been trying to use this plugin on Windows and when I add the plugin to my lein user profile and start a repl with `lein repl`, values are printed with the ANSI escape characters (I think this is what's happening). 

![image](https://user-images.githubusercontent.com/12722744/44301771-7724a900-a2e2-11e8-86f6-de0d22457561.png)

This happens in powershell (which I use as my VSCode integrated terminal), as well as cmd. I did notice that Console Emulator does display the colors correctly. I don't know if this is an OS issue, a terminal settings issue, or an issue with Ultra (I'm thinking not). Could someone shed some light on how I might be able to allow colors in the powershell terminal?

**Comment by bpringe** [comment]
I just want to give a solution I just came across with some research and trial and error, in case others using VSCode have this issue. I downloaded ANSICON, then in my VSCode User Settings, I set the following values so that I could run powershell from ansicon for the integrated terminal.
```javascript
"terminal.integrated.shell.windows": "C:\\Program Files\\ansi184\\x64\\ansicon.exe", // make this your path to ansicon
"terminal.integrated.shellArgs.windows": ["powershell"]
```
Now the color feature of Ultra works in the integrated powershell terminal in VSCode. However, is there a way to make this work by default on Windows? I'm all about making other avenues of entry for new Clojurians easier (i.e. Windows users). Thanks for the great plugin.

**Comment by venantius** [comment]
I'm afraid I'm pretty ignorant as to the workings of powershell or most Windows terminal options. However, the color highlighting in Ultra at the terminal level is powered by [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code), which Windows supposedly only started supporting fairly recently. 

Anyways, to be claer - this isn't an OS issue, it's a specific reader feature present in a terminal emulator that knows how to handle the relevant escape codes (which are otherwise just plain old text characters). Some terminals will support it out-of-the-box, others may require additional plugins or settings to be toggled to turn it on. 

As this isn't a bug per say I'm going to close this issue since hopefully the above explanation is sufficient to point anyone having difficulty in the right direction to figuring out a relevant solution for their given terminal of choice.
